name: Trigger auto deployment for container-app-omvcuilrmrmbq

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-omvcuilrmrmbq-AutoDeployTrigger-70606550-3f13-4b7b-82ed-4208e9f8de38.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPOMVCUILRMRMBQ_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPOMVCUILRMRMBQ_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPOMVCUILRMRMBQ_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistryomvcuilrmrmbq.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPOMVCUILRMRMBQ_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPOMVCUILRMRMBQ_REGISTRY_PASSWORD }}
          containerAppName: container-app-omvcuilrmrmbq
          resourceGroup: playtodo9a55
          imageToBuild: containerregistryomvcuilrmrmbq.azurecr.io/container-app-omvcuilrmrmbq:${{ github.sha }}
          


